import PublicNav from "@/components/PublicNav";
import PublicFooter from "@/components/PublicFooter";
import { Zap } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <PublicNav />

      <div className="pt-28 pb-20 px-6 max-w-3xl mx-auto flex-1">
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-primary/10 mb-6">
            <Zap className="w-7 h-7 text-primary" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight mb-3">
            Terms of <span className="gradient-text">Service</span>
          </h1>
          <p className="text-foreground/50 text-sm">Last updated: May 28, 2026</p>
        </div>

        <div className="space-y-8">
          <Section title="The Short Version">
            <p>Repurposely helps you repurpose YouTube video content into posts for other platforms. You own the content you create. Don&apos;t abuse the service. Pay for what you use. We&apos;ll do our best to keep things running. That&apos;s the gist.</p>
          </Section>

          <Section title="Using Repurposely">
            <p>By creating an account, you agree to these terms. To use Repurposely, you must:</p>
            <ul>
              <li>Be at least 13 years old.</li>
              <li>Provide accurate account information.</li>
              <li>Keep your password secure.</li>
              <li>Use the service in compliance with all applicable laws.</li>
            </ul>
          </Section>

          <Section title="Your Content">
            <p><strong>You own what you create.</strong> All content generated through Repurposely belongs to you. We don&apos;t claim any ownership over your generated tweets, scripts, posts, or any other output.</p>
            <p>However, you&apos;re responsible for:</p>
            <ul>
              <li>Ensuring you have the right to repurpose the source YouTube videos.</li>
              <li>Reviewing and editing AI-generated content before publishing.</li>
              <li>The accuracy of anything you post using our generated content.</li>
              <li>Complying with each platform&apos;s terms of service when posting.</li>
            </ul>
          </Section>

          <Section title="YouTube Content & Fair Use">
            <p>Repurposely extracts transcripts from publicly available YouTube videos. You are responsible for ensuring your use of repurposed content complies with copyright law and fair use principles.</p>
            <ul>
              <li>Repurposing ideas and knowledge from videos is generally acceptable.</li>
              <li>Copying content word-for-word without attribution may violate copyright.</li>
              <li>We recommend adding your own perspective and value to all generated content.</li>
              <li>If a content creator requests removal of content derived from their video, we expect you to comply.</li>
            </ul>
          </Section>

          <Section title="AI-Generated Content Disclaimer">
            <p>Content generated by Repurposely is created by artificial intelligence. While we work hard to make it accurate and high-quality:</p>
            <ul>
              <li>AI can make mistakes. Always review content before publishing.</li>
              <li>Generated content may not perfectly represent the source video&apos;s message.</li>
              <li>We don&apos;t guarantee that generated content will perform well on any platform.</li>
              <li>You are solely responsible for anything you publish using our output.</li>
            </ul>
          </Section>

          <Section title="Subscriptions & Payments">
            <ul>
              <li><strong>Free plan:</strong> 3 generations per month. No credit card required.</li>
              <li><strong>Paid plans:</strong> Billed monthly through Stripe. Prices are listed on our pricing page.</li>
              <li><strong>Cancellation:</strong> Cancel anytime from your Settings page. You keep access until the end of your billing period.</li>
              <li><strong>Refunds:</strong> Full refund within 7 days of your first paid subscription. After that, no refunds for partial months.</li>
              <li><strong>Price changes:</strong> We&apos;ll give you 30 days notice before any price increases.</li>
            </ul>
          </Section>

          <Section title="What You Can't Do">
            <p>Don&apos;t use Repurposely to:</p>
            <ul>
              <li>Generate spam or misleading content at scale.</li>
              <li>Violate anyone&apos;s copyright or intellectual property.</li>
              <li>Impersonate other creators or brands.</li>
              <li>Share your account credentials with others (get a team plan instead).</li>
              <li>Reverse engineer, scrape, or abuse our API.</li>
              <li>Generate content that&apos;s illegal, harmful, or hateful.</li>
            </ul>
            <p>We reserve the right to suspend or terminate accounts that violate these terms.</p>
          </Section>

          <Section title="Service Availability">
            <p>We aim for high uptime but can&apos;t guarantee 100% availability. We may:</p>
            <ul>
              <li>Experience occasional downtime for maintenance or updates.</li>
              <li>Modify or discontinue features with reasonable notice.</li>
              <li>Limit usage during periods of unusually high demand.</li>
            </ul>
            <p>We&apos;ll do our best to communicate any planned disruptions in advance.</p>
          </Section>

          <Section title="Limitation of Liability">
            <p>Repurposely is provided &ldquo;as is.&rdquo; To the maximum extent permitted by law:</p>
            <ul>
              <li>We&apos;re not liable for any indirect, incidental, or consequential damages.</li>
              <li>Our total liability is limited to the amount you&apos;ve paid us in the last 12 months.</li>
              <li>We&apos;re not responsible for losses from content you publish using our service.</li>
            </ul>
          </Section>

          <Section title="Changes to These Terms">
            <p>We may update these terms from time to time. For significant changes, we&apos;ll notify you by email at least 30 days before they take effect. Continued use of the service after changes means you accept the new terms.</p>
          </Section>

          <Section title="Contact">
            <p>Questions about these terms? Email us at <strong>support@repurposely.com</strong>.</p>
          </Section>
        </div>
      </div>

      <PublicFooter />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="relative bg-[#111113] border border-[#1e1e24] rounded-2xl p-6 hover:border-primary/20 transition-all">
      <div className="absolute top-0 left-6 right-6 h-[1px] bg-gradient-to-r from-transparent via-primary/20 to-transparent" />
      <h2 className="text-lg font-bold text-white mb-3">{title}</h2>
      <div className="text-sm text-foreground/60 leading-relaxed space-y-2 [&_ul]:list-disc [&_ul]:ml-5 [&_ul]:space-y-1.5 [&_strong]:text-white">
        {children}
      </div>
    </div>
  );
}
